# upload_server/docker-compose.yml
services:
  fastapi_uploader:
    build: .
    container_name: offline_upload_server
    ports:
      - "8001:8000"
    volumes:
      # 현재 위치(upload_server)에서 한 단계 상위 폴더(../)의
      # server/recordings 폴더를 컨테이너의 /data 폴더와 연결
      - ../server/recordings:/data