# upload_server/docker-compose.yml
services:
  fastapi_uploader:
    build: .
    container_name: ${CONTAINER_NAME}
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - ${HOST_SAVE_PATH}:${CONTAINER_DATA_PATH}
    env_file:
      - .env
    # uvicorn 실행 시 .env의 CONTAINER_PORT 변수를 사용하도록 설정
    command: uvicorn app.main:app --host 0.0.0.0 --port ${CONTAINER_PORT}