# docker-compose.yml
services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "${MEDIAMTX_SRT_PORT}:8890/udp"   # SRT 입력
      - "${MEDIAMTX_CHECK_PORT}:9997"

    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
      - ${MEDIAMTX_REC_PATH}:/recordings   # 녹화 저장 경로