services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8890:8890/udp"   # SRT 입력
      - "9997:9997"

    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
      - ./recordings:/recordings   # 녹화 저장 경로
