services:
  server:
    build: .
    container_name: db-upload-server
    volumes:
      - ../server/recordings:/app/../server/recordings
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - STATUS_SERVER_URL=${STATUS_SERVER_URL}